name: GithubActions Pipeline CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        - with:
          otp-version: '23.0'
          elixir-version: '1.11.0'
      name: deps
        run: mix deps.get
      name: LINT CODE
        run: mix credo --strict
